# Generated by Django 5.2.6 on 2025-10-06 12:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25)),
                ('nome', models.CharField(default='Sem nome', max_length=100)),
                ('descricao', models.TextField()),
                ('quantidade', models.IntegerField()),
                ('marca', models.CharField(max_length=120)),
                ('fornecedor', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('qtd_min', models.IntegerField()),
                ('qtd_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabela', models.CharField(max_length=50)),
                ('acao', models.CharField(max_length=10)),
                ('registro_id', models.IntegerField()),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'estoque_auditoria',
            },
        ),
    ]
