# Generated by Django 5.2.6 on 2025-10-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25)),
                ('descricao', models.TextField()),
                ('quantidade', models.IntegerField()),
                ('marca', models.CharField(max_length=120)),
                ('fornecedor', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('qtd_min', models.IntegerField()),
                ('qtd_max', models.IntegerField()),
            ],
        ),
    ]
