# Generated by Django 5.2.6 on 2025-10-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('localizacao', models.CharField(blank=True, max_length=100)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Ativa', 'Ativa'), ('Em manutenção', 'Em manutenção'), ('Inativa', 'Inativa')], default='Ativa', max_length=20)),
                ('pecas', models.ManyToManyField(related_name='maquinas', to='estoque.estoque')),
            ],
        ),
    ]
