# Generated by Django 5.2.6 on 2025-11-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_maquina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='tabela',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='fornecedor',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='marca',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='nome',
            field=models.CharField(default='Sem nome', max_length=25),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='localizacao',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='nome',
            field=models.CharField(max_length=25),
        ),
    ]
