# Generated by Django 5.2.6 on 2025-11-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_auditoria_tabela_alter_estoque_fornecedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='nome',
            field=models.CharField(max_length=25),
        ),
    ]
